controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:

    base_frame_id: base_link

    joints:
      - fl_rotation_joint
      - fr_rotation_joint
      - rl_rotation_joint
      - rr_rotation_joint
      - camera_base_joint
      - left_camera_joint
      - right_camera_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort

forward_velocity_controller:
  ros__parameters:

    base_frame_id: base_link

    joints:
      - fl_wheel_joint
      - fr_wheel_joint
      - rl_wheel_joint
      - rr_wheel_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
